# Install from curl
# https://distrobox.it/#curl-or-wget

- name: Install latest Distrobox
  ansible.builtin.shell: curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh
  args:
    creates: /usr/bin/distrobox
  become: true